export const links = [{
  name: 'AAAI-23 - KGTK: User-friendly Toolkit for Manipulation of Large Knowledge Graphs',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mi leo, ultrices vehicula enim quis, consequat pharetra tellus. Pellentesque viverra placerat ultrices. Curabitur lacinia enim arcu, ac tristique mauris fermentum id. Cras varius erat lectus. Suspendisse sit amet purus quis nibh molestie ullamcorper. Ut at malesuada diam. Vestibulum congue risus id purus dignissim gravida. Cras nunc magna, vehicula non mattis ut, gravida consectetur nisl. Integer tristique nibh iaculis quam suscipit aliquet. Donec vel leo arcu. Pellentesque a aliquam justo, quis tincidunt nisl. Sed ultricies placerat arcu maximus auctor. Suspendisse sit amet sapien nisl. Suspendisse in purus interdum, consequat urna semper, malesuada orci. Curabitur suscipit sed risus sit amet malesuada.',
  url: 'https://usc-isi-i2.github.io/kgtk-tutorial-aaai-2023/',
  image: 'https://raw.githubusercontent.com/usc-isi-i2/kgtk-website/develop/src/images/tutorials/temp.jpg',
}, {
  name: '01-kgtk-introduction',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mi leo, ultrices vehicula enim quis, consequat pharetra tellus. Pellentesque viverra placerat ultrices. Curabitur lacinia enim arcu, ac tristique mauris fermentum id. Cras varius erat lectus. Suspendisse sit amet purus quis nibh molestie ullamcorper. Ut at malesuada diam. Vestibulum congue risus id purus dignissim gravida. Cras nunc magna, vehicula non mattis ut, gravida consectetur nisl. Integer tristique nibh iaculis quam suscipit aliquet. Donec vel leo arcu. Pellentesque a aliquam justo, quis tincidunt nisl. Sed ultricies placerat arcu maximus auctor. Suspendisse sit amet sapien nisl. Suspendisse in purus interdum, consequat urna semper, malesuada orci. Curabitur suscipit sed risus sit amet malesuada.',
  url: 'https://colab.research.google.com/drive/1dQeJSYQwpNdIvC9H00SQ90usiUgu3o1E?usp=sharing',
  image: 'https://raw.githubusercontent.com/usc-isi-i2/kgtk-website/develop/src/images/tutorials/temp.jpg',
}, {
  name: '02-kg-profiling',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mi leo, ultrices vehicula enim quis, consequat pharetra tellus. Pellentesque viverra placerat ultrices. Curabitur lacinia enim arcu, ac tristique mauris fermentum id. Cras varius erat lectus. Suspendisse sit amet purus quis nibh molestie ullamcorper. Ut at malesuada diam. Vestibulum congue risus id purus dignissim gravida. Cras nunc magna, vehicula non mattis ut, gravida consectetur nisl. Integer tristique nibh iaculis quam suscipit aliquet. Donec vel leo arcu. Pellentesque a aliquam justo, quis tincidunt nisl. Sed ultricies placerat arcu maximus auctor. Suspendisse sit amet sapien nisl. Suspendisse in purus interdum, consequat urna semper, malesuada orci. Curabitur suscipit sed risus sit amet malesuada.',
  url: 'https://colab.research.google.com/drive/1jwq_vVWWwiEa8izA0UZZ_CMK1qIMxBQh?usp=sharing',
  image: 'https://raw.githubusercontent.com/usc-isi-i2/kgtk-website/develop/src/images/tutorials/temp.jpg',
}, {
  name: '03-kg-graph-embeddings',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mi leo, ultrices vehicula enim quis, consequat pharetra tellus. Pellentesque viverra placerat ultrices. Curabitur lacinia enim arcu, ac tristique mauris fermentum id. Cras varius erat lectus. Suspendisse sit amet purus quis nibh molestie ullamcorper. Ut at malesuada diam. Vestibulum congue risus id purus dignissim gravida. Cras nunc magna, vehicula non mattis ut, gravida consectetur nisl. Integer tristique nibh iaculis quam suscipit aliquet. Donec vel leo arcu. Pellentesque a aliquam justo, quis tincidunt nisl. Sed ultricies placerat arcu maximus auctor. Suspendisse sit amet sapien nisl. Suspendisse in purus interdum, consequat urna semper, malesuada orci. Curabitur suscipit sed risus sit amet malesuada.',
  url: 'https://colab.research.google.com/drive/1Fl4_5LLEtapOxtVlo57hwpPzEK1gFViL?usp=sharing',
  image: 'https://raw.githubusercontent.com/usc-isi-i2/kgtk-website/develop/src/images/tutorials/temp.jpg',
}, {
  name: '04-kg-enrichment-with-csv',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mi leo, ultrices vehicula enim quis, consequat pharetra tellus. Pellentesque viverra placerat ultrices. Curabitur lacinia enim arcu, ac tristique mauris fermentum id. Cras varius erat lectus. Suspendisse sit amet purus quis nibh molestie ullamcorper. Ut at malesuada diam. Vestibulum congue risus id purus dignissim gravida. Cras nunc magna, vehicula non mattis ut, gravida consectetur nisl. Integer tristique nibh iaculis quam suscipit aliquet. Donec vel leo arcu. Pellentesque a aliquam justo, quis tincidunt nisl. Sed ultricies placerat arcu maximus auctor. Suspendisse sit amet sapien nisl. Suspendisse in purus interdum, consequat urna semper, malesuada orci. Curabitur suscipit sed risus sit amet malesuada.',
  url: 'https://colab.research.google.com/drive/1tqKvFTFFQoBCA9GZ5WZPVJhJq5fBem49?usp=sharing',
  image: 'https://raw.githubusercontent.com/usc-isi-i2/kgtk-website/develop/src/images/tutorials/temp.jpg',
}, {
  name: '05-kg-enrichment-with-lod',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mi leo, ultrices vehicula enim quis, consequat pharetra tellus. Pellentesque viverra placerat ultrices. Curabitur lacinia enim arcu, ac tristique mauris fermentum id. Cras varius erat lectus. Suspendisse sit amet purus quis nibh molestie ullamcorper. Ut at malesuada diam. Vestibulum congue risus id purus dignissim gravida. Cras nunc magna, vehicula non mattis ut, gravida consectetur nisl. Integer tristique nibh iaculis quam suscipit aliquet. Donec vel leo arcu. Pellentesque a aliquam justo, quis tincidunt nisl. Sed ultricies placerat arcu maximus auctor. Suspendisse sit amet sapien nisl. Suspendisse in purus interdum, consequat urna semper, malesuada orci. Curabitur suscipit sed risus sit amet malesuada.',
  url: 'https://colab.research.google.com/drive/1vXttxSVtJeSDPlCrpL88G6TGhXdoC3ve?usp=sharing',
  image: 'https://raw.githubusercontent.com/usc-isi-i2/kgtk-website/develop/src/images/tutorials/temp.jpg',
}, {
  name: '06-kg-network-analysis',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mi leo, ultrices vehicula enim quis, consequat pharetra tellus. Pellentesque viverra placerat ultrices. Curabitur lacinia enim arcu, ac tristique mauris fermentum id. Cras varius erat lectus. Suspendisse sit amet purus quis nibh molestie ullamcorper. Ut at malesuada diam. Vestibulum congue risus id purus dignissim gravida. Cras nunc magna, vehicula non mattis ut, gravida consectetur nisl. Integer tristique nibh iaculis quam suscipit aliquet. Donec vel leo arcu. Pellentesque a aliquam justo, quis tincidunt nisl. Sed ultricies placerat arcu maximus auctor. Suspendisse sit amet sapien nisl. Suspendisse in purus interdum, consequat urna semper, malesuada orci. Curabitur suscipit sed risus sit amet malesuada.',
  url: 'https://colab.research.google.com/drive/1Lat732XpHv1RMswoYsz_wUk_6eKEf8Xt?usp=sharing',
  image: 'https://raw.githubusercontent.com/usc-isi-i2/kgtk-website/develop/src/images/tutorials/temp.jpg',
}, {
  name: '07-kg-constraint-validation',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce mi leo, ultrices vehicula enim quis, consequat pharetra tellus. Pellentesque viverra placerat ultrices. Curabitur lacinia enim arcu, ac tristique mauris fermentum id. Cras varius erat lectus. Suspendisse sit amet purus quis nibh molestie ullamcorper. Ut at malesuada diam. Vestibulum congue risus id purus dignissim gravida. Cras nunc magna, vehicula non mattis ut, gravida consectetur nisl. Integer tristique nibh iaculis quam suscipit aliquet. Donec vel leo arcu. Pellentesque a aliquam justo, quis tincidunt nisl. Sed ultricies placerat arcu maximus auctor. Suspendisse sit amet sapien nisl. Suspendisse in purus interdum, consequat urna semper, malesuada orci. Curabitur suscipit sed risus sit amet malesuada.',
  url: 'https://colab.research.google.com/drive/182ikHCeGDhyPs8WuLQC03c-ET84p0ozM?usp=sharing',
  image: 'https://raw.githubusercontent.com/usc-isi-i2/kgtk-website/develop/src/images/tutorials/temp.jpg',
}]
